### ISSUE TITLE
Create oemof foundation [legal person]

### ISSUE THREAD

**Issue by busiing** [oemof/organisation#44]
This issue was created to continue the discussion about the creation of an oemof foundation.

This topic was discussed at the oemof dev/user meeting may 2019. Now it is necessary to get feedback of the whole oemof community

> Benefits of a foundation:
> 
> 1. Representation of oemof as an organisation that is independent from the participating institutes.
> 2. Fixing the non-valid copyright as "oemof developer".
> 3. A foundation would be able to accept donations.
> 4. A foundation would give an additional trust in the stability of the oemof group
> 5. People would feel more responsible
> 6. 5 euro Conference fee could be collected for dev/user meetings
> 
> Open questions:
> 
> 1. How would decisions be made?
> 2. Could only members decide?
> 3. Who would be allowed to become a member under which conditions?
> 4. Or would the decision process be separated from the foundation and go on as usual?
> 
> Arguments against a foundation:
> 
> 1. It is not clear how the foundation would alter the representation of the institutes. The website oemof.org already equally presents the participating institutes.
> 2. Much work to establish institutionalized structures.
> 3. It would not be possible to donate from project.
> 4. It is much easier to finance something like "homepage hosting" in projects.
> 
> Examples of foundations:
> 
> - FSFE (Free Software Foundation Europe) e.V.
> - openEMS as an example for a software foundation

 [protocoll](https://github.com/oemof/organisation/wiki/Meeting-May-2019)

Let's discuss the listed issues 🤓

**Comment by busiing** [comment]
I propose that we set up a task force to deal with the progress of this issue. The task force could be made up of members who are in fact the legal persons implementing the creation of the foundation.

Open points:

- [ ] Open Questions
- [ ] Set Deadline for Decision (Y/N foundation)
- [ ] Create Task Force (at least 7 members)
- [ ] Create Foundation (if)

**Comment by busiing** [comment]
Push:
@jnnr @uvchik @gnn @p-snft @c-moeller @FranziPl @joroeder

**Comment by p-snft** [comment]
I'd suggest to first ask for the feelings at RLI and ZNES, on how a foundation would influence their support.

**Comment by busiing** [comment]
> I'd suggest to first ask for the feelings at RLI and ZNES, on how a foundation would influence their support.

**Push:** 
@uvchik @gnn @simnh @c-moeller @ckaldemeyer @FranziPl @henhuy @SabineHaas 

**Task:** 
Please describe your feelings towards an oemof foundation!

- [ ] Feelings of your institution
- [ ] Feeling of you as a developer or as a person ;-)
- [ ] Feeling of the person who gets the overhead or behaves like a boss

**Comment by jnnr** [comment]
Thanks for reviving this topic, busiing! After some reflection and talking to my team, I can note some opinions, thoughts and ideas (and feelings :).

**Voices/experiences from my institution**
When putting it up for discussion in our regular meeting of our research area, I got the feedback that, if the group of developers decide to take that step, we want to support the initiative. We see the advantage of a foundation as a way to keep oemof and the community alive and developing. Until today, oemof has succeeded to grow with its light-weight organisation. The hope is that the foundation puts oemof on more solid legs to enable it to walk another 5 years or longer. If we as the oemof community decide to do so, it would be a 

Some remarks/experiences by my colleagues:
* Registering a foundation has some initial costs for registration, paying a notary.
* There is some work required setting up a foundation's statute (describing how to enter the foundation, decision processes etc.).
* What will be the membership fee? Experience tells that 200-400 Eur/a are the minimal requirement to sustain a foundation.
* Will the foundation be serving public good (gemeinnützig)?
* How much time do members spend for the foundation? 
* How to prevent annoying overhead, bureaucracy, conflicts and ideosyncratic club dynamics (Vereinsmeierei)?
* Are there more examples of OSS-projects embodied by a foundation? Maybe some smaller projects could be a good example.

Some more examples of foundations (to be continued)
* Energieseminar in Berlin
* Einleuchtend e.V.

**My thoughts**
Most of the people that have experiences with clubs acquired them in sports clubs. There is a certain stereotype which has its dark sides (bureaucracy, rules, paralysis, no fun). Better not to get trapped in this wrong picture!

I see both the potential problems and the advantages. In the best case, the foundation render the sustainable development and maintenance of oemof more reliable. The initiative has the chance to make some organisational things more explicit. This will of course require some work. But I guess that we can learn a lot from other projects and also from our own, which is exciting.

**Comment by p-snft** [comment]
> Will the foundation be serving public good (gemeinnützig)?

I would assume so. Funding of research allows to make the association to be a recognized charity. And being one allows for tax reliefs - also for those who give funds or pay membership fees. Also, being a member in or giving money to a recognized charity is no problem for other recognized charities. At last, it reduces the needed bureaucracy. For example, the tax has to be declared every third year.

> Registering a foundation has some initial costs for registration, paying a notary.

In some federal states, there is no fee for recognized charities.

> There is some work required setting up a foundation's statute (describing how to enter the foundation, decision processes etc.).

Indeed. I guess, this will be most of the work. After, the statue is designed, it can go to an informal review to the finance authorities who then can comment on whether it will allow to be recognized as a charity.

> What will be the membership fee? Experience tells that 200-400 Eur/a are the minimal requirement to sustain a foundation.

The minimal additional costs (besides the web page that is already run) would be a bank account. This currently costs about 10€ / mo. 

> How much time do members spend for the foundation?

Additional affords are a yearly financial report and a yearly general assembly. The former can be very brief but needs to be checked by two persons who were not involved in creating it. The latter could also be performed online.

> How to prevent annoying overhead, bureaucracy, conflicts and ideosyncratic club dynamics (Vereinsmeierei)?

To my estimation, the overhead can be kept rather low (see above). From my experience in computer related clubs, the most dangerous dynamics would be that nobody is willing to organize the tasks to maintain the structure. But similar things are true for a non-formalized dev community.

> Are there more examples of OSS-projects embodied by a foundation? Maybe some smaller projects could be a good example.

There are of course the bigger, well-known examples like, e.g. OpenFOAM for simulation. Really small projects often just have a "development team". Examples for none-industry foundations on [list of free and open-source software organizations at Wikipedia](https://en.wikipedia.org/wiki/List_of_free_and_open-source_software_organizations) include the ones for Krita and VLC.

**Comment by p-snft** [comment]
I came to another question: Who will be members? Just natural persons or also corporate entities? I am asking because of the funding. @jnnr assumed that the foundations budget could be covered by membership fees. But I see three possible ways:

1. Member institutes could provide higher membership fees than individual members.
2. Institutes might also become sponsors.
3. Option two may be exclusive by only allowing natural persons to become members. (This would avoid problems when one institute does not want to be a formal member because of legal doubts but wants equal rights with other institutes.)

**Comment by busiing** [comment]
The pros and cons might be a good thing to discuss, but...

isn't there the necessity of having an institution like a club to protect the work of all of us.

Is the license of our code (oemof) enough reason to create an oemof foundation (what so ever)?

So I hope that we can get a little more attention to the open points:

How do the institutes "feel" about being in a club or supporting one?
Push:
@uvchik @gnn @simnh @c-moeller @ckaldemeyer @FranziPl @henhuy @SabineHaas

**Comment by busiing** [comment]
Protocoll of dev meeting dec 2019:

"- oemof foundation:
    - Präsentation von Steffen ist hier zu finden: xxxx
    - Anmeldegebühr für developer meetings als (freiwillige) Kosten, nicht als Spende, damit abrechenbar als Dienstreisekosten
    - Zweck des Vereins: Treffen der oemof Community und Weiterentwicklung von oemof fördern
    - alle drei Jahre muss Gemeinnützigkeit überprüft werden
    - Vorteile: oemof repräsentieren unabhängig von den beteiligten Institutionen; Spenden können angenommen werden
    - könnte aber auch Nachteil sein, dass die Mitglieder vom oemof-Verein getrennt werden von der oemof-Community und sich andere ausgegrenzt fühlen
    - Es müssen 7 Mitglieder sein --> können das auch Institutionen sein?
    - alle sind sich einig, dass der Verein nicht den Charakter der offenen Community einschränken soll, Transparenz erfolgt weiter auf GitHub, z. B. PR mit Satzung
    - Weiteres Vorgehen: für alle kritischen offenen Punkte jeweils Issue eröffnen, um zu diskutieren + Deadline --> Steffen"

**Comment by p-snft** [comment]
> Es müssen 7 Mitglieder sein --> können das auch Institutionen sein?

By law, it is allowed to have not only natural persons but also legal entities as members. However, the foundations constitution may state something different. This might be advised, e.g. if institutes that want to contribute relevant amounts cannot be members because of their own rules. These might be reluctant to do so if other (possibly smaller) contributors got more visibility due to a formal membership.

**Comment by busiing** [comment]
The discussed the pros and cons at the dev meeting 2020 (december). A poll of the public opinion showed that the majority was in favour of establishing an oemof foundation.

Main pros:
- The association supports the continuing work on oemof
- 

- Its purpose: Organising the meetings of the oemof community and promoting further development of oemof
- We need at least 7 members
- Financing: Registration fee for developer meetings as (voluntary) costs, not as a donation, thus chargeable as business travel expenses
- the association must not restrict the character of the open community, transparency continues on GitHub, e.g. PR with charter

At the meeting, the mood towards the establishment of an oemof foundation was positive. In order to give the community the opportunity to speak out against this development, we have decided to set a deadline of 2 months. The deadline is therefore 04.05.2020.

Further issues will be addressed separately in related issues:
#60 Creation of an oemof foundation charter (Satzung)
#61 Support of the oemof foundation via institutes

**Comment by busiing** [comment]
Update:
Feelings of institutions checked:
(Yes = checked box, No = unchecked box)
- [ ] RLI
- [ ] Beuth
- [ ] Flensburg
- [ ] Oldenburg (DLR)
- [ ] Oldenburg (OFFIS)
- [ ] Bremen

**Comment by beierd** [comment]
I checked the box for Bremen but what exactly is meant by feelings? Feeling that creating a foundation might be a good idea? :)

**Comment by busiing** [comment]
> I'd suggest to first ask for the feelings at RLI and ZNES, **on how a foundation would influence their support.**

@p-snft mentioned this as it might be a sensitive topic to lose "control" over oemof  (I assume)

**Comment by christian-rli** [comment]
Hi all, I stumbled across this issue, after looking for possible pro reasons that could speak in favour of creating an association for the open energy family. This issue helped me out, so thank you for that. Also, I have a couple remarks I'd like to share here:

1. I believe the option you are investigating here is not a foundation ("Stiftung"), but an association ("Verein"). A foundation, like the FSFE (or Wikimedia, or Mozilla) have a pile of money that they can live off. openEMS (I mention this, because it is listed above) is in fact an association, as (I'm assuming this) there is no pile of money. This might just be a nitpicky remark and I also think "foundation" sounds cooler than "association", but I also think the difference between the two is rather relevant.
2. Free software under German law is most unfortunately not in the [list of the charitable causes](https://www.gesetze-im-internet.de/ao_1977/__52.html) (however, science and research is). So you should probably be careful when defining your association goals.

**Comment by christian-rli** [comment]
Vielleicht auch relevant: https://www.golem.de/news/freie-software-gemeinnuetzigkeit-as-a-service-gibt-es-auch-in-europa-1702-126056.html

**Comment by p-snft** [comment]
Thanks, @christian-rli for pointing this out.

1. We are really thinking about creating an association. The name was probably influenced by the FSFE which to my knowledge also is an association - despite the name. Still, this might become an issue, as some people at the register of associations are really picky.
2. I already considered this in a [draft for the statute](https://github.com/oemof/oemof/blob/feature/foundation/legal/satzung.md).
